### ISSUE TITLE
Prestashop - Use the correct ISO code

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-prestashop#74]
In the installation, to create the search engines, the country's ISO code is currently being sent. We have to send the language code, only the first 2 characters of the code that Prestashop has.
For example:
en-gb -> en
es-mx -> es
es -> es

- Review other features of the plugin in which you use the ISO code and modify it. For example, when displaying the layer's script, API calls,...

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-prestashop/74?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @alvanieto @eduardogomez97 @ivan-doofinder @sofia-doofinder

**Comment by sofia-doofinder** [comment]
@ivan-doofinder some weeks ago we had an issue related with this short codes in magento. @Aitor-Corrales knows about it. The problem is that we can have customers that have for example pt-PT and pt-BR, and as we're spliting the language we have just pt. This is perfect for the SE language because elasticsearch need this value, but we've troubles in the installation because we can't have twice the "pt" language so we've a conflict with the layer languages - search engines.

We was thinking that maybe we can send always the full code and in the create-store endpoint split the code for the SE and keep it completed for the layer. But it means that magento and woocomerce needs to be checked also...
