### ISSUE TITLE
Prestashop - Fix "Overwrite Search page with Doofinder results"

### ISSUE THREAD

**Issue by CristobalDolz** [doofinder/doofinder-prestashop#84]
A store in Prestashop can have Doofinder installed and have the search layer disabled but use the feature "Overwrite Search page with Doofinder results" to replace the results given by Prestashop.

search query = "not"

results given by default with prestashop 
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/f776fac2-1c3d-42a7-a649-3df01b535df2)

results must be shown with Doofinder results
![image.png](https://images.zenhubusercontent.com/628cb9457cf2e60aa1ac50de/43c7de60-6efb-40f5-8e84-ec013d42602b)

**Comment by alexgonbled** [comment]
I have this problem

**Comment by eduardogomez97** [comment]
I seem to remember that this functionality was done when we had the v7 layer, because the user gave enter and jumped the prestashop results page with different results to those that came out in the layer, then this was done so that the results were the same. But with v9, I think Ivan knows this for sure, it should not be necessary because the submit is already controlled in the layer itself or something like that I remember he said.

Can you confirm this question? @ivan-doofinder

**Comment by ivan-doofinder** [comment]
It is a functionality that stopped working when the plugin was released for the livelayer version (v4.0 of the plugin). I think it was because the fullscreen didn't allow clicking "Enter" with the layer open.

**Comment by eduardogomez97** [comment]
After talking it over with Ivan I have found out that this function is no longer available since version 0.4 of the plugin. So it would not be a bug.

I understand that the option would have to be removed from the panel? since it is a function that was chosen to be discarded. @CristobalDolz

**Comment by CristobalDolz** [comment]
So, remove that option please. thanks!
